SELECT rec.RecoveryId, 
       rec.Agency, 
	   rec.RunYear, 
	   rec.RecoverySite, 
	   rec.RecoveryDate, 
	   rec.Species, 
	   rec.CWDBFishery, 
	   rec.Fishery as FisheryID, 
	   fishery.Description as FisheryName, 
	   rec.Sex, 
	   rec.Length, 
	   rec.LengthCode, 
	   rec.Age, 
	   rec.TagStatus, 
	   rec.TagCode, 
	   rec.DetectionMethod, 
	   rec.RecordedMark, 
	   rec.SampleType, 
	   rec.SamplingPeriodType, 
	   rec.SamplingPeriodNumber, 
	   rec.EstimatedNumber, 
	   rec.AdjustedEstimatedNumber, 
	   rec.EstimationLevel, 
	   rec.CatchSampleId, 
	   rec.Extrapolated, 
	   rec.ExtrapolatedRecoveryId, 
	   rec.Auxiliary
FROM ${fishery_tbl_name} fishery INNER JOIN ${rec_tbl_name} rec ON fishery.Id = rec.Fishery;

